services:
  simpleaccountservice:
    image: ${DOCKER_REGISTRY-}simpleaccountservice
    ports:
      - "8080:8080"
      - "8081:8081"
    build:
      context: .
      dockerfile: SimpleAccountService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      KEYCLOAK_URL: "http://keycloak:8080"
      KEYCLOAK_REALM: "my_realm"
      KEYCLOAK_CLIENT_ID: "my_client"
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    command:
    - start-dev
    - "-Dkeycloak.migration.action=import"
    - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    - "-Dkeycloak.migration.provider=singleFile"
    - "-Dkeycloak.migration.file=/opt/keycloak/data/import/my_realm-realm.json"
    ports:
      - "8180:8080"
    environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        KEYCLOAK_IMPORT_LOG_LEVEL: DEBUG
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import:ro